---
title: "Code Book"
author: "Le Gru"
date: "27. September 2015"
output: html_document
---
## Code Book

The data in this data set is derived from http://archive.ics.uci.edu/ml/datasets/Human+Activity+Recognition+Using+Smartphones 
The cleaning process adopted is described in the related R script: "run_analysis.R"

The variales 

* user: contains the id of the users.  In our case the values are: "1"  "10" "11" "12" "13" "14" "15" "16" "17" "18" "19" "2"  "20" "21" "22" "23" "24" "25" "26" "27" "28" "29" "3"  "30" "4"  "5"  "6"  "7"  "8"  "9" 

* activities: contains the activities performed during the tests.  The values are: "LAYING"             "SITTING"            "STANDING"           "WALKING"           "WALKING\_DOWNSTAIRS" "WALKING\_UPSTAIRS"     

The meaning of the remaining variables is described in the text  below taken verbatim  from the code book of the original data.  Please note  that only mean and std  (standard deviation) values aare considered here.  The value in the data set  is the mean of the values in the dta  set for each condition: user X activity

Description of the variable meanings (verbatim  from the code book of the original data)

The features selected for this database come from the accelerometer and gyroscope 3-axial raw signals tAcc-XYZ and tGyro-XYZ. These time domain signals (prefix 't' to denote time) were captured at a constant rate of 50 Hz. Then they were filtered using a median filter and a 3rd order low pass Butterworth filter with a corner frequency of 20 Hz to remove noise. Similarly, the acceleration signal was then separated into body and gravity acceleration signals (tBodyAcc-XYZ and tGravityAcc-XYZ) using another low pass Butterworth filter with a corner frequency of 0.3 Hz. 

Subsequently, the body linear acceleration and angular velocity were derived in time to obtain Jerk signals (tBodyAccJerk-XYZ and tBodyGyroJerk-XYZ). Also the magnitude of these three-dimensional signals were calculated using the Euclidean norm (tBodyAccMag, tGravityAccMag, tBodyAccJerkMag, tBodyGyroMag, tBodyGyroJerkMag). 

Finally a Fast Fourier Transform (FFT) was applied to some of these signals producing fBodyAcc-XYZ, fBodyAccJerk-XYZ, fBodyGyro-XYZ, fBodyAccJerkMag, fBodyGyroMag, fBodyGyroJerkMag. (Note the 'f' to indicate frequency domain signals). 

These signals were used to estimate variables of the feature vector for each pattern:  
'-XYZ' is used to denote 3-axial signals in the X, Y and Z directions.

tBodyAcc-XYZ
tGravityAcc-XYZ
tBodyAccJerk-XYZ
tBodyGyro-XYZ
tBodyGyroJerk-XYZ
tBodyAccMag
tGravityAccMag
tBodyAccJerkMag
tBodyGyroMag
tBodyGyroJerkMag
fBodyAcc-XYZ
fBodyAccJerk-XYZ
fBodyGyro-XYZ
fBodyAccMag
fBodyAccJerkMag
fBodyGyroMag
fBodyGyroJerkMag